# -*- coding: utf-8 -*-
"""Data Analisis Sederhana

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DNEoZJ3lb2KGnqNlKaWmqwBUv5Xi0R2g
"""

# Import library utama
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data = {
    'Bulan' : ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Juni', 'Jul', 'Aug', 'sep', 'Okt', 'Nov', 'Des'],
    'Penjualan' : [1200, 1500, 1400, 1300,1250, 1000,1350,1100,1010,1600,1570,1900],
    'Biaya Iklan' : [300,100,200,400,250,600,260,100,130,150,100,400]

}
df = pd.DataFrame(data)
df

Total_penjualan = df['Penjualan'].sum()
print(f"Total Penjualan : {Total_penjualan}")

Rata_rata_penjualan = round(df['Penjualan'].mean(),2)
print(f"Rata-rata Penjualan : {Rata_rata_penjualan}")

bulan_tertinggi = df[df['Penjualan'] == df['Penjualan'].max()]
print(f"Bulan dengan Penjualan Tertinggi :")
bulan_tertinggi

plt.figure(figsize=(10,6))
sns.lineplot(x='Bulan', y='Penjualan', data=df, marker='o')
plt.title('Grafik Penjualan Bulanan', fontsize=16)
plt.xlabel('Bulan', fontsize=12)
plt.ylabel('Penjualan', fontsize=12)
plt.grid()
plt.show()

plt.figure(figsize=(8,6))
sns.scatterplot(x='Biaya Iklan', y='Penjualan', data=df)
plt.title('Grafik Penjualan terhadap Biaya Iklan', fontsize=16)
plt.xlabel('Biaya Iklan', fontsize=12)
plt.ylabel('Penjualan', fontsize=12)
plt.grid()
plt.show()